server:
  port: 8080
spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 123456
logging:
  level:
    org:
      neo4j:
        driver:
          GraphDatabase: debug
          Driver: debug
          OutboundMessageHandler: debug
          InboundMessageDispatcher: debug
